-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.checklists (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  week_number integer NOT NULL,
  year integer NOT NULL,
  forklift_model text NOT NULL DEFAULT ''::text,
  forklift_serial text NOT NULL DEFAULT ''::text,
  forklift_number text NOT NULL DEFAULT ''::text,
  shift text NOT NULL DEFAULT '1'::text,
  items jsonb NOT NULL DEFAULT '[]'::jsonb,
  operator_signatures jsonb NOT NULL DEFAULT '{}'::jsonb,
  supervisor_signatures jsonb NOT NULL DEFAULT '{}'::jsonb,
  notes text NOT NULL DEFAULT ''::text,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'submitted'::text, 'reviewed'::text, 'approved'::text])),
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  supervisor_reviewed_days jsonb DEFAULT '[]'::jsonb CHECK (jsonb_typeof(supervisor_reviewed_days) = 'array'::text),
  supervisor_reviewed_at timestamp with time zone,
  CONSTRAINT checklists_pkey PRIMARY KEY (id),
  CONSTRAINT checklists_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.issues (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  title text NOT NULL,
  description text,
  image_before text NOT NULL,
  image_after text,
  status text DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'in_progress'::text, 'done'::text])),
  priority text DEFAULT 'medium'::text CHECK (priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text])),
  x_percent double precision NOT NULL,
  y_percent double precision NOT NULL,
  area text DEFAULT ''::text,
  category text DEFAULT ''::text,
  created_by uuid,
  assigned_to uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  due_date timestamp with time zone,
  closed_at timestamp with time zone,
  completed_by uuid,
  history jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT issues_pkey PRIMARY KEY (id),
  CONSTRAINT issues_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT issues_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.users(id),
  CONSTRAINT issues_completed_by_fkey FOREIGN KEY (completed_by) REFERENCES public.users(id)
);
CREATE TABLE public.robot_checklists (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  month integer NOT NULL CHECK (month >= 1 AND month <= 12),
  year integer NOT NULL,
  robot_model text NOT NULL DEFAULT ''::text,
  robot_number text NOT NULL DEFAULT ''::text,
  area text NOT NULL DEFAULT 'MROBOT'::text,
  items jsonb NOT NULL DEFAULT '[]'::jsonb,
  operator_signatures jsonb NOT NULL DEFAULT '{}'::jsonb,
  supervisor_signatures jsonb NOT NULL DEFAULT '{}'::jsonb,
  notes text NOT NULL DEFAULT ''::text,
  incidents jsonb NOT NULL DEFAULT '[]'::jsonb,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'submitted'::text, 'reviewed'::text, 'approved'::text])),
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  supervisor_reviewed_days jsonb DEFAULT '[]'::jsonb CHECK (jsonb_typeof(supervisor_reviewed_days) = 'array'::text),
  supervisor_reviewed_at timestamp with time zone,
  CONSTRAINT robot_checklists_pkey PRIMARY KEY (id),
  CONSTRAINT robot_checklists_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.truck_check_results (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  form_id uuid,
  template_id text,
  status text CHECK (status = ANY (ARRAY['pass'::text, 'fail'::text])),
  remark text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT truck_check_results_pkey PRIMARY KEY (id),
  CONSTRAINT truck_check_results_form_id_fkey FOREIGN KEY (form_id) REFERENCES public.truck_exit_forms(id),
  CONSTRAINT truck_check_results_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.truck_checklist_templates(id)
);
CREATE TABLE public.truck_checklist_templates (
  id text NOT NULL,
  label_en text NOT NULL,
  label_vi text NOT NULL,
  order_index integer NOT NULL UNIQUE,
  CONSTRAINT truck_checklist_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.truck_exit_forms (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  form_no text DEFAULT lpad((nextval('truck_form_no_seq'::regclass))::text, 7, '0'::text) UNIQUE,
  date date,
  customer_name text,
  description text,
  truck_no text,
  truck_size text,
  driver_name text,
  net_weight numeric,
  gate_in_time timestamp with time zone,
  gate_out_time timestamp with time zone,
  doc_time timestamp with time zone,
  dock_time timestamp with time zone,
  start_loading_time timestamp with time zone,
  end_loading_time timestamp with time zone,
  remarks text,
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'submitted'::text, 'approved'::text])),
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  invoice_nos ARRAY NOT NULL,
  quantities ARRAY,
  dock_nos ARRAY,
  checked_bys ARRAY,
  created_by_ids ARRAY DEFAULT '{}'::text[],
  CONSTRAINT truck_exit_forms_pkey PRIMARY KEY (id),
  CONSTRAINT truck_exit_forms_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.truck_signatures (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  form_id uuid NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['driver'::text, 'security'::text, 'warehouse'::text, 'approver'::text])),
  user_id uuid,
  user_name text,
  signature_url text,
  signed_at timestamp with time zone DEFAULT now(),
  signed_by_role text CHECK (signed_by_role = ANY (ARRAY['operator'::text, 'warehouse'::text, 'driver'::text, 'security'::text, 'approver'::text])),
  signed_by_name text,
  CONSTRAINT truck_signatures_pkey PRIMARY KEY (id),
  CONSTRAINT truck_signatures_form_id_fkey FOREIGN KEY (form_id) REFERENCES public.truck_exit_forms(id),
  CONSTRAINT truck_signatures_user_fk FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  email text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['admin'::text, 'operator'::text, 'supervisor'::text])),
  active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  signature_url text,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
